#pragma once

#define IDD_NEWTILESET_DIALOG                   23000

#define IDC_TILESET_NAME                        23001
#define IDC_TILESET_IMAGE_PATH                  23002
#define IDC_TILESET_BROWSE_IMAGE_BUTTON         23003
#define IDC_TILESET_TILE_WIDTH                  23004
#define IDC_TILESET_TILE_HEIGHT                 23005
#define IDC_TILESET_LABEL_TILESET_NAME          23006
#define IDC_TILESET_LABEL_IMAGE_PATH            23007
#define IDC_TILESET_LABEL_TILE_WIDTH            23008
#define IDC_TILESET_LABEL_TILE_HEIGHT           23009
#define IDC_TILESET_INCLUDE_PACKAGE_CHECKBOX    23010
#define IDC_TILESET_PACKAGE_COMBO               23011
#define IDC_TILESET_NEW_PACKAGE_BUTTON          23012
#define IDC_TILESET_LABEL_PACKAGE               23013
